name: '🐛 Bug Report'
description: 'Bugs, missing documentation, or unexpected behavior 🤔.'
labels: ['🐛 fix']
title: 'fix: '
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for creating an issue 😄!

        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!

        We're all volunteers here, so help us help you by taking the time to
        accurately fill out this template. ❤️
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A brief description of the issue.'
      placeholder: |
        When I ____, I expected ____ to happen but ____ happened instead.
    validations:
      required: true
  - type: 'input'
    id: 'reproduction'
    attributes:
      label: 'Link to Reproduction'
      description: |
        A link to a CodeSandbox reproduction which demonstrates the bug
      placeholder: 'https://codesandbox.io/'
  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to reproduce'
      description: |
        Explain how to cause the issue in the provided reproduction.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.
